interface DataType {
  firstName: string;
  lastName: string;
  age: number;
  visits: number;
  progress: number;
  status: "relationship" | "complicated" | "single";
}

export const data: DataType[] = [
  {
    firstName: "ant",
    lastName: "offer",
    age: 21,
    visits: 45,
    progress: 81,
    status: "single",
  },
  {
    firstName: "ant",
    lastName: "offer",
    age: 21,
    visits: 45,
    progress: 81,
    status: "single",
  },
  {
    firstName: "ant",
    lastName: "offer",
    age: 21,
    visits: 45,
    progress: 81,
    status: "single",
  },
  {
    firstName: "ant",
    lastName: "offer",
    age: 21,
    visits: 45,
    progress: 81,
    status: "single",
  },
  {
    firstName: "ant",
    lastName: "offer",
    age: 21,
    visits: 45,
    progress: 81,
    status: "single",
  },
  {
    firstName: "ant",
    lastName: "offer",
    age: 21,
    visits: 45,
    progress: 81,
    status: "single",
  },
  {
    firstName: "ant",
    lastName: "offer",
    age: 21,
    visits: 45,
    progress: 81,
    status: "single",
  },
  {
    firstName: "ant",
    lastName: "offer",
    age: 21,
    visits: 45,
    progress: 81,
    status: "single",
  },
  {
    firstName: "ant",
    lastName: "offer",
    age: 21,
    visits: 45,
    progress: 81,
    status: "single",
  },
  {
    firstName: "ant",
    lastName: "offer",
    age: 21,
    visits: 45,
    progress: 81,
    status: "single",
  },
  {
    firstName: "ant",
    lastName: "offer",
    age: 21,
    visits: 45,
    progress: 81,
    status: "single",
  },
  {
    firstName: "ant",
    lastName: "offer",
    age: 21,
    visits: 45,
    progress: 81,
    status: "single",
  },
  {
    firstName: "ant",
    lastName: "offer",
    age: 21,
    visits: 45,
    progress: 81,
    status: "single",
  },
  {
    firstName: "ant",
    lastName: "offer",
    age: 21,
    visits: 45,
    progress: 81,
    status: "single",
  },
  {
    firstName: "ant",
    lastName: "offer",
    age: 21,
    visits: 45,
    progress: 81,
    status: "single",
  },
  {
    firstName: "ant",
    lastName: "offer",
    age: 21,
    visits: 45,
    progress: 81,
    status: "single",
  },
  {
    firstName: "ant",
    lastName: "offer",
    age: 21,
    visits: 45,
    progress: 81,
    status: "single",
  },
  {
    firstName: "ant",
    lastName: "offer",
    age: 21,
    visits: 45,
    progress: 81,
    status: "single",
  },
];
